// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 02 Oct 2022 19:40:55 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "AppCore/CAPI.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// ULUpdateCallback_7e1c6355 is a proxy for callback ULUpdateCallback.
void ULUpdateCallback_7e1c6355(void* user_data);

// ULCloseCallback_195b2f9 is a proxy for callback ULCloseCallback.
void ULCloseCallback_195b2f9(void* user_data);

// ULResizeCallback_6e7309d9 is a proxy for callback ULResizeCallback.
void ULResizeCallback_6e7309d9(void* user_data, unsigned int width, unsigned int height);

// ULChangeTitleCallback_bd58034c is a proxy for callback ULChangeTitleCallback.
void ULChangeTitleCallback_bd58034c(void* user_data, ULView caller, ULString title);

// ULChangeURLCallback_4ec32b80 is a proxy for callback ULChangeURLCallback.
void ULChangeURLCallback_4ec32b80(void* user_data, ULView caller, ULString url);

// ULChangeTooltipCallback_12ca407 is a proxy for callback ULChangeTooltipCallback.
void ULChangeTooltipCallback_12ca407(void* user_data, ULView caller, ULString tooltip);

// ULChangeCursorCallback_1a7011df is a proxy for callback ULChangeCursorCallback.
void ULChangeCursorCallback_1a7011df(void* user_data, ULView caller, ULCursor cursor);

// ULAddConsoleMessageCallback_44b8dd01 is a proxy for callback ULAddConsoleMessageCallback.
void ULAddConsoleMessageCallback_44b8dd01(void* user_data, ULView caller, ULMessageSource source, ULMessageLevel level, ULString message, unsigned int line_number, unsigned int column_number, ULString source_id);

// ULCreateChildViewCallback_ef6d2cdd is a proxy for callback ULCreateChildViewCallback.
ULView ULCreateChildViewCallback_ef6d2cdd(void* user_data, ULView caller, ULString opener_url, ULString target_url, _Bool is_popup, ULIntRect popup_rect);

// ULBeginLoadingCallback_70d8c0ad is a proxy for callback ULBeginLoadingCallback.
void ULBeginLoadingCallback_70d8c0ad(void* user_data, ULView caller, unsigned long long frame_id, _Bool is_main_frame, ULString url);

// ULFinishLoadingCallback_1ed4ecae is a proxy for callback ULFinishLoadingCallback.
void ULFinishLoadingCallback_1ed4ecae(void* user_data, ULView caller, unsigned long long frame_id, _Bool is_main_frame, ULString url);

// ULFailLoadingCallback_55ff90b8 is a proxy for callback ULFailLoadingCallback.
void ULFailLoadingCallback_55ff90b8(void* user_data, ULView caller, unsigned long long frame_id, _Bool is_main_frame, ULString url, ULString description, ULString error_domain, int error_code);

// ULWindowObjectReadyCallback_66dc25f3 is a proxy for callback ULWindowObjectReadyCallback.
void ULWindowObjectReadyCallback_66dc25f3(void* user_data, ULView caller, unsigned long long frame_id, _Bool is_main_frame, ULString url);

// ULDOMReadyCallback_6432c207 is a proxy for callback ULDOMReadyCallback.
void ULDOMReadyCallback_6432c207(void* user_data, ULView caller, unsigned long long frame_id, _Bool is_main_frame, ULString url);

// ULUpdateHistoryCallback_6e105364 is a proxy for callback ULUpdateHistoryCallback.
void ULUpdateHistoryCallback_6e105364(void* user_data, ULView caller);

// ULSurfaceDefinitionCreateCallback_573ec115 is a proxy for callback ULSurfaceDefinitionCreateCallback.
void* ULSurfaceDefinitionCreateCallback_573ec115(unsigned int width, unsigned int height);

// ULSurfaceDefinitionDestroyCallback_851bacee is a proxy for callback ULSurfaceDefinitionDestroyCallback.
void ULSurfaceDefinitionDestroyCallback_851bacee(void* user_data);

// ULSurfaceDefinitionGetWidthCallback_1a49a8fd is a proxy for callback ULSurfaceDefinitionGetWidthCallback.
unsigned int ULSurfaceDefinitionGetWidthCallback_1a49a8fd(void* user_data);

// ULSurfaceDefinitionGetHeightCallback_3e5fe408 is a proxy for callback ULSurfaceDefinitionGetHeightCallback.
unsigned int ULSurfaceDefinitionGetHeightCallback_3e5fe408(void* user_data);

// ULSurfaceDefinitionGetRowBytesCallback_adcc8668 is a proxy for callback ULSurfaceDefinitionGetRowBytesCallback.
unsigned int ULSurfaceDefinitionGetRowBytesCallback_adcc8668(void* user_data);

// ULSurfaceDefinitionGetSizeCallback_83184afe is a proxy for callback ULSurfaceDefinitionGetSizeCallback.
unsigned long int ULSurfaceDefinitionGetSizeCallback_83184afe(void* user_data);

// ULSurfaceDefinitionLockPixelsCallback_7763e12f is a proxy for callback ULSurfaceDefinitionLockPixelsCallback.
void* ULSurfaceDefinitionLockPixelsCallback_7763e12f(void* user_data);

// ULSurfaceDefinitionUnlockPixelsCallback_d4b69f9 is a proxy for callback ULSurfaceDefinitionUnlockPixelsCallback.
void ULSurfaceDefinitionUnlockPixelsCallback_d4b69f9(void* user_data);

// ULSurfaceDefinitionResizeCallback_22d82567 is a proxy for callback ULSurfaceDefinitionResizeCallback.
void ULSurfaceDefinitionResizeCallback_22d82567(void* user_data, unsigned int width, unsigned int height);

// ULFileSystemFileExistsCallback_d03bf100 is a proxy for callback ULFileSystemFileExistsCallback.
_Bool ULFileSystemFileExistsCallback_d03bf100(ULString path);

// ULFileSystemGetFileSizeCallback_e87ad8b1 is a proxy for callback ULFileSystemGetFileSizeCallback.
_Bool ULFileSystemGetFileSizeCallback_e87ad8b1(int handle, long long* result);

// ULFileSystemGetFileMimeTypeCallback_7e6fd322 is a proxy for callback ULFileSystemGetFileMimeTypeCallback.
_Bool ULFileSystemGetFileMimeTypeCallback_7e6fd322(ULString path, ULString result);

// ULFileSystemOpenFileCallback_bbb19604 is a proxy for callback ULFileSystemOpenFileCallback.
int ULFileSystemOpenFileCallback_bbb19604(ULString path, _Bool open_for_writing);

// ULFileSystemCloseFileCallback_c90ac2e5 is a proxy for callback ULFileSystemCloseFileCallback.
void ULFileSystemCloseFileCallback_c90ac2e5(int handle);

// ULFileSystemReadFromFileCallback_bc1997bc is a proxy for callback ULFileSystemReadFromFileCallback.
long long ULFileSystemReadFromFileCallback_bc1997bc(int handle, char* data, long long length);

// ULLoggerLogMessageCallback_454e682a is a proxy for callback ULLoggerLogMessageCallback.
void ULLoggerLogMessageCallback_454e682a(ULLogLevel log_level, ULString message);

// ULGPUDriverBeginSynchronizeCallback_650938c is a proxy for callback ULGPUDriverBeginSynchronizeCallback.
void ULGPUDriverBeginSynchronizeCallback_650938c();

// ULGPUDriverEndSynchronizeCallback_f6baad4d is a proxy for callback ULGPUDriverEndSynchronizeCallback.
void ULGPUDriverEndSynchronizeCallback_f6baad4d();

// ULGPUDriverNextTextureIdCallback_7de045b4 is a proxy for callback ULGPUDriverNextTextureIdCallback.
unsigned int ULGPUDriverNextTextureIdCallback_7de045b4();

// ULGPUDriverCreateTextureCallback_a32244d8 is a proxy for callback ULGPUDriverCreateTextureCallback.
void ULGPUDriverCreateTextureCallback_a32244d8(unsigned int texture_id, ULBitmap bitmap);

// ULGPUDriverUpdateTextureCallback_3d7a526 is a proxy for callback ULGPUDriverUpdateTextureCallback.
void ULGPUDriverUpdateTextureCallback_3d7a526(unsigned int texture_id, ULBitmap bitmap);

// ULGPUDriverDestroyTextureCallback_a8eea310 is a proxy for callback ULGPUDriverDestroyTextureCallback.
void ULGPUDriverDestroyTextureCallback_a8eea310(unsigned int texture_id);

// ULGPUDriverNextRenderBufferIdCallback_bfeb3fb8 is a proxy for callback ULGPUDriverNextRenderBufferIdCallback.
unsigned int ULGPUDriverNextRenderBufferIdCallback_bfeb3fb8();

// ULGPUDriverCreateRenderBufferCallback_68ee5367 is a proxy for callback ULGPUDriverCreateRenderBufferCallback.
void ULGPUDriverCreateRenderBufferCallback_68ee5367(unsigned int render_buffer_id, ULRenderBuffer buffer);

// ULGPUDriverDestroyRenderBufferCallback_81623f13 is a proxy for callback ULGPUDriverDestroyRenderBufferCallback.
void ULGPUDriverDestroyRenderBufferCallback_81623f13(unsigned int render_buffer_id);

// ULGPUDriverNextGeometryIdCallback_5f2a8fea is a proxy for callback ULGPUDriverNextGeometryIdCallback.
unsigned int ULGPUDriverNextGeometryIdCallback_5f2a8fea();

// ULGPUDriverCreateGeometryCallback_5957236d is a proxy for callback ULGPUDriverCreateGeometryCallback.
void ULGPUDriverCreateGeometryCallback_5957236d(unsigned int geometry_id, ULVertexBuffer vertices, ULIndexBuffer indices);

// ULGPUDriverUpdateGeometryCallback_3f20997 is a proxy for callback ULGPUDriverUpdateGeometryCallback.
void ULGPUDriverUpdateGeometryCallback_3f20997(unsigned int geometry_id, ULVertexBuffer vertices, ULIndexBuffer indices);

// ULGPUDriverDestroyGeometryCallback_cce3a508 is a proxy for callback ULGPUDriverDestroyGeometryCallback.
void ULGPUDriverDestroyGeometryCallback_cce3a508(unsigned int geometry_id);

// ULGPUDriverUpdateCommandListCallback_d3815a9e is a proxy for callback ULGPUDriverUpdateCommandListCallback.
void ULGPUDriverUpdateCommandListCallback_d3815a9e(ULCommandList list);

// ULClipboardClearCallback_eda3036a is a proxy for callback ULClipboardClearCallback.
void ULClipboardClearCallback_eda3036a();

// ULClipboardReadPlainTextCallback_fedfb2b6 is a proxy for callback ULClipboardReadPlainTextCallback.
void ULClipboardReadPlainTextCallback_fedfb2b6(ULString result);

// ULClipboardWritePlainTextCallback_6e8e0ca4 is a proxy for callback ULClipboardWritePlainTextCallback.
void ULClipboardWritePlainTextCallback_6e8e0ca4(ULString text);

// JSTypedArrayBytesDeallocator_68d51f83 is a proxy for callback JSTypedArrayBytesDeallocator.
void JSTypedArrayBytesDeallocator_68d51f83(void* bytes, void* deallocatorContext);

// JSObjectInitializeCallback_5793b16 is a proxy for callback JSObjectInitializeCallback.
void JSObjectInitializeCallback_5793b16(JSContextRef ctx, JSObjectRef object);

// JSObjectInitializeCallbackEx_3f9a093b is a proxy for callback JSObjectInitializeCallbackEx.
void JSObjectInitializeCallbackEx_3f9a093b(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object);

// JSObjectFinalizeCallback_93da0aea is a proxy for callback JSObjectFinalizeCallback.
void JSObjectFinalizeCallback_93da0aea(JSObjectRef object);

// JSObjectFinalizeCallbackEx_d64d3113 is a proxy for callback JSObjectFinalizeCallbackEx.
void JSObjectFinalizeCallbackEx_d64d3113(JSClassRef jsClass, JSObjectRef object);

// JSObjectHasPropertyCallback_340bfa95 is a proxy for callback JSObjectHasPropertyCallback.
_Bool JSObjectHasPropertyCallback_340bfa95(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName);

// JSObjectHasPropertyCallbackEx_c35701e7 is a proxy for callback JSObjectHasPropertyCallbackEx.
_Bool JSObjectHasPropertyCallbackEx_c35701e7(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object, JSStringRef propertyName);

// JSObjectGetPropertyCallback_5caec716 is a proxy for callback JSObjectGetPropertyCallback.
JSValueRef JSObjectGetPropertyCallback_5caec716(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName, JSValueRef* exception);

// JSObjectGetPropertyCallbackEx_8b91eedb is a proxy for callback JSObjectGetPropertyCallbackEx.
JSValueRef JSObjectGetPropertyCallbackEx_8b91eedb(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object, JSStringRef propertyName, JSValueRef* exception);

// JSObjectSetPropertyCallback_a684f1fe is a proxy for callback JSObjectSetPropertyCallback.
_Bool JSObjectSetPropertyCallback_a684f1fe(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName, JSValueRef value, JSValueRef* exception);

// JSObjectSetPropertyCallbackEx_d28cf88c is a proxy for callback JSObjectSetPropertyCallbackEx.
_Bool JSObjectSetPropertyCallbackEx_d28cf88c(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object, JSStringRef propertyName, JSValueRef value, JSValueRef* exception);

// JSObjectDeletePropertyCallback_b0108ebe is a proxy for callback JSObjectDeletePropertyCallback.
_Bool JSObjectDeletePropertyCallback_b0108ebe(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName, JSValueRef* exception);

// JSObjectDeletePropertyCallbackEx_e24fcdb0 is a proxy for callback JSObjectDeletePropertyCallbackEx.
_Bool JSObjectDeletePropertyCallbackEx_e24fcdb0(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object, JSStringRef propertyName, JSValueRef* exception);

// JSObjectGetPropertyNamesCallback_e77d2329 is a proxy for callback JSObjectGetPropertyNamesCallback.
void JSObjectGetPropertyNamesCallback_e77d2329(JSContextRef ctx, JSObjectRef object, JSPropertyNameAccumulatorRef propertyNames);

// JSObjectGetPropertyNamesCallbackEx_74285955 is a proxy for callback JSObjectGetPropertyNamesCallbackEx.
void JSObjectGetPropertyNamesCallbackEx_74285955(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object, JSPropertyNameAccumulatorRef propertyNames);

// JSObjectCallAsFunctionCallback_89f9469b is a proxy for callback JSObjectCallAsFunctionCallback.
JSValueRef JSObjectCallAsFunctionCallback_89f9469b(JSContextRef ctx, JSObjectRef function, JSObjectRef thisObject, unsigned long int argumentCount, JSValueRef* arguments, JSValueRef* exception);

// JSObjectCallAsFunctionCallbackEx_9f036e3c is a proxy for callback JSObjectCallAsFunctionCallbackEx.
JSValueRef JSObjectCallAsFunctionCallbackEx_9f036e3c(JSContextRef ctx, JSClassRef jsClass, JSStringRef className, JSObjectRef function, JSObjectRef thisObject, unsigned long int argumentCount, JSValueRef* arguments, JSValueRef* exception);

// JSObjectCallAsConstructorCallback_45f4b71f is a proxy for callback JSObjectCallAsConstructorCallback.
JSObjectRef JSObjectCallAsConstructorCallback_45f4b71f(JSContextRef ctx, JSObjectRef constructor, unsigned long int argumentCount, JSValueRef* arguments, JSValueRef* exception);

// JSObjectCallAsConstructorCallbackEx_a563df4 is a proxy for callback JSObjectCallAsConstructorCallbackEx.
JSObjectRef JSObjectCallAsConstructorCallbackEx_a563df4(JSContextRef ctx, JSClassRef jsClass, JSObjectRef constructor, unsigned long int argumentCount, JSValueRef* arguments, JSValueRef* exception);

// JSObjectHasInstanceCallback_aa527d2e is a proxy for callback JSObjectHasInstanceCallback.
_Bool JSObjectHasInstanceCallback_aa527d2e(JSContextRef ctx, JSObjectRef constructor, JSValueRef possibleInstance, JSValueRef* exception);

// JSObjectHasInstanceCallbackEx_b7bafe4e is a proxy for callback JSObjectHasInstanceCallbackEx.
_Bool JSObjectHasInstanceCallbackEx_b7bafe4e(JSContextRef ctx, JSClassRef jsClass, JSObjectRef constructor, JSValueRef possibleInstance, JSValueRef* exception);

// JSObjectConvertToTypeCallback_d379d61c is a proxy for callback JSObjectConvertToTypeCallback.
JSValueRef JSObjectConvertToTypeCallback_d379d61c(JSContextRef ctx, JSObjectRef object, JSType _type, JSValueRef* exception);

// JSObjectConvertToTypeCallbackEx_1bcea974 is a proxy for callback JSObjectConvertToTypeCallbackEx.
JSValueRef JSObjectConvertToTypeCallbackEx_1bcea974(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object, JSType _type, JSValueRef* exception);

