// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 07 Oct 2019 13:59:36 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void ULUpdateCallback_7e1c6355(void* user_data) {
	uLUpdateCallback7E1C6355(user_data);
}

void ULCloseCallback_195b2f9(void* user_data) {
	uLCloseCallback195B2F9(user_data);
}

void ULResizeCallback_6e7309d9(void* user_data, unsigned int width, unsigned int height) {
	uLResizeCallback6E7309D9(user_data, width, height);
}

void ULChangeTitleCallback_bd58034c(void* user_data, ULView caller, ULString title) {
	uLChangeTitleCallbackBD58034C(user_data, caller, title);
}

void ULChangeURLCallback_4ec32b80(void* user_data, ULView caller, ULString url) {
	uLChangeURLCallback4EC32B80(user_data, caller, url);
}

void ULChangeTooltipCallback_12ca407(void* user_data, ULView caller, ULString tooltip) {
	uLChangeTooltipCallback12CA407(user_data, caller, tooltip);
}

void ULChangeCursorCallback_1a7011df(void* user_data, ULView caller, ULCursor cursor) {
	uLChangeCursorCallback1A7011DF(user_data, caller, cursor);
}

void ULAddConsoleMessageCallback_44b8dd01(void* user_data, ULView caller, ULMessageSource source, ULMessageLevel level, ULString message, unsigned int line_number, unsigned int column_number, ULString source_id) {
	uLAddConsoleMessageCallback44B8DD01(user_data, caller, source, level, message, line_number, column_number, source_id);
}

void ULBeginLoadingCallback_70d8c0ad(void* user_data, ULView caller) {
	uLBeginLoadingCallback70D8C0AD(user_data, caller);
}

void ULFinishLoadingCallback_1ed4ecae(void* user_data, ULView caller) {
	uLFinishLoadingCallback1ED4ECAE(user_data, caller);
}

void ULUpdateHistoryCallback_6e105364(void* user_data, ULView caller) {
	uLUpdateHistoryCallback6E105364(user_data, caller);
}

void ULDOMReadyCallback_6432c207(void* user_data, ULView caller) {
	uLDOMReadyCallback6432C207(user_data, caller);
}

void JSTypedArrayBytesDeallocator_68d51f83(void* bytes, void* deallocatorContext) {
	jSTypedArrayBytesDeallocator68D51F83(bytes, deallocatorContext);
}

void JSObjectInitializeCallback_5793b16(JSContextRef ctx, JSObjectRef object) {
	jSObjectInitializeCallback5793B16(ctx, object);
}

void JSObjectFinalizeCallback_93da0aea(JSObjectRef object) {
	jSObjectFinalizeCallback93DA0AEA(object);
}

_Bool JSObjectHasPropertyCallback_340bfa95(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName) {
	return jSObjectHasPropertyCallback340BFA95(ctx, object, propertyName);
}

JSValueRef JSObjectGetPropertyCallback_5caec716(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName, JSValueRef* exception) {
	return jSObjectGetPropertyCallback5CAEC716(ctx, object, propertyName, exception);
}

_Bool JSObjectSetPropertyCallback_a684f1fe(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName, JSValueRef value, JSValueRef* exception) {
	return jSObjectSetPropertyCallbackA684F1FE(ctx, object, propertyName, value, exception);
}

_Bool JSObjectDeletePropertyCallback_b0108ebe(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName, JSValueRef* exception) {
	return jSObjectDeletePropertyCallbackB0108EBE(ctx, object, propertyName, exception);
}

void JSObjectGetPropertyNamesCallback_e77d2329(JSContextRef ctx, JSObjectRef object, JSPropertyNameAccumulatorRef propertyNames) {
	jSObjectGetPropertyNamesCallbackE77D2329(ctx, object, propertyNames);
}

JSValueRef JSObjectCallAsFunctionCallback_89f9469b(JSContextRef ctx, JSObjectRef function, JSObjectRef thisObject, unsigned long int argumentCount, JSValueRef* arguments, JSValueRef* exception) {
	return jSObjectCallAsFunctionCallback89F9469B(ctx, function, thisObject, argumentCount, arguments, exception);
}

JSObjectRef JSObjectCallAsConstructorCallback_45f4b71f(JSContextRef ctx, JSObjectRef constructor, unsigned long int argumentCount, JSValueRef* arguments, JSValueRef* exception) {
	return jSObjectCallAsConstructorCallback45F4B71F(ctx, constructor, argumentCount, arguments, exception);
}

_Bool JSObjectHasInstanceCallback_aa527d2e(JSContextRef ctx, JSObjectRef constructor, JSValueRef possibleInstance, JSValueRef* exception) {
	return jSObjectHasInstanceCallbackAA527D2E(ctx, constructor, possibleInstance, exception);
}

JSValueRef JSObjectConvertToTypeCallback_d379d61c(JSContextRef ctx, JSObjectRef object, JSType _type, JSValueRef* exception) {
	return jSObjectConvertToTypeCallbackD379D61C(ctx, object, _type, exception);
}

