// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 02 Oct 2022 19:40:55 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void ULUpdateCallback_7e1c6355(void* user_data) {
	uLUpdateCallback7E1C6355(user_data);
}

void ULCloseCallback_195b2f9(void* user_data) {
	uLCloseCallback195B2F9(user_data);
}

void ULResizeCallback_6e7309d9(void* user_data, unsigned int width, unsigned int height) {
	uLResizeCallback6E7309D9(user_data, width, height);
}

void ULChangeTitleCallback_bd58034c(void* user_data, ULView caller, ULString title) {
	uLChangeTitleCallbackBD58034C(user_data, caller, title);
}

void ULChangeURLCallback_4ec32b80(void* user_data, ULView caller, ULString url) {
	uLChangeURLCallback4EC32B80(user_data, caller, url);
}

void ULChangeTooltipCallback_12ca407(void* user_data, ULView caller, ULString tooltip) {
	uLChangeTooltipCallback12CA407(user_data, caller, tooltip);
}

void ULChangeCursorCallback_1a7011df(void* user_data, ULView caller, ULCursor cursor) {
	uLChangeCursorCallback1A7011DF(user_data, caller, cursor);
}

void ULAddConsoleMessageCallback_44b8dd01(void* user_data, ULView caller, ULMessageSource source, ULMessageLevel level, ULString message, unsigned int line_number, unsigned int column_number, ULString source_id) {
	uLAddConsoleMessageCallback44B8DD01(user_data, caller, source, level, message, line_number, column_number, source_id);
}

ULView ULCreateChildViewCallback_ef6d2cdd(void* user_data, ULView caller, ULString opener_url, ULString target_url, _Bool is_popup, ULIntRect popup_rect) {
	return uLCreateChildViewCallbackEF6D2CDD(user_data, caller, opener_url, target_url, is_popup, popup_rect);
}

void ULBeginLoadingCallback_70d8c0ad(void* user_data, ULView caller, unsigned long long frame_id, _Bool is_main_frame, ULString url) {
	uLBeginLoadingCallback70D8C0AD(user_data, caller, frame_id, is_main_frame, url);
}

void ULFinishLoadingCallback_1ed4ecae(void* user_data, ULView caller, unsigned long long frame_id, _Bool is_main_frame, ULString url) {
	uLFinishLoadingCallback1ED4ECAE(user_data, caller, frame_id, is_main_frame, url);
}

void ULFailLoadingCallback_55ff90b8(void* user_data, ULView caller, unsigned long long frame_id, _Bool is_main_frame, ULString url, ULString description, ULString error_domain, int error_code) {
	uLFailLoadingCallback55FF90B8(user_data, caller, frame_id, is_main_frame, url, description, error_domain, error_code);
}

void ULWindowObjectReadyCallback_66dc25f3(void* user_data, ULView caller, unsigned long long frame_id, _Bool is_main_frame, ULString url) {
	uLWindowObjectReadyCallback66DC25F3(user_data, caller, frame_id, is_main_frame, url);
}

void ULDOMReadyCallback_6432c207(void* user_data, ULView caller, unsigned long long frame_id, _Bool is_main_frame, ULString url) {
	uLDOMReadyCallback6432C207(user_data, caller, frame_id, is_main_frame, url);
}

void ULUpdateHistoryCallback_6e105364(void* user_data, ULView caller) {
	uLUpdateHistoryCallback6E105364(user_data, caller);
}

void* ULSurfaceDefinitionCreateCallback_573ec115(unsigned int width, unsigned int height) {
	return uLSurfaceDefinitionCreateCallback573EC115(width, height);
}

void ULSurfaceDefinitionDestroyCallback_851bacee(void* user_data) {
	uLSurfaceDefinitionDestroyCallback851BACEE(user_data);
}

unsigned int ULSurfaceDefinitionGetWidthCallback_1a49a8fd(void* user_data) {
	return uLSurfaceDefinitionGetWidthCallback1A49A8FD(user_data);
}

unsigned int ULSurfaceDefinitionGetHeightCallback_3e5fe408(void* user_data) {
	return uLSurfaceDefinitionGetHeightCallback3E5FE408(user_data);
}

unsigned int ULSurfaceDefinitionGetRowBytesCallback_adcc8668(void* user_data) {
	return uLSurfaceDefinitionGetRowBytesCallbackADCC8668(user_data);
}

unsigned long int ULSurfaceDefinitionGetSizeCallback_83184afe(void* user_data) {
	return uLSurfaceDefinitionGetSizeCallback83184AFE(user_data);
}

void* ULSurfaceDefinitionLockPixelsCallback_7763e12f(void* user_data) {
	return uLSurfaceDefinitionLockPixelsCallback7763E12F(user_data);
}

void ULSurfaceDefinitionUnlockPixelsCallback_d4b69f9(void* user_data) {
	uLSurfaceDefinitionUnlockPixelsCallbackD4B69F9(user_data);
}

void ULSurfaceDefinitionResizeCallback_22d82567(void* user_data, unsigned int width, unsigned int height) {
	uLSurfaceDefinitionResizeCallback22D82567(user_data, width, height);
}

_Bool ULFileSystemFileExistsCallback_d03bf100(ULString path) {
	return uLFileSystemFileExistsCallbackD03BF100(path);
}

_Bool ULFileSystemGetFileSizeCallback_e87ad8b1(int handle, long long* result) {
	return uLFileSystemGetFileSizeCallbackE87AD8B1(handle, result);
}

_Bool ULFileSystemGetFileMimeTypeCallback_7e6fd322(ULString path, ULString result) {
	return uLFileSystemGetFileMimeTypeCallback7E6FD322(path, result);
}

int ULFileSystemOpenFileCallback_bbb19604(ULString path, _Bool open_for_writing) {
	return uLFileSystemOpenFileCallbackBBB19604(path, open_for_writing);
}

void ULFileSystemCloseFileCallback_c90ac2e5(int handle) {
	uLFileSystemCloseFileCallbackC90AC2E5(handle);
}

long long ULFileSystemReadFromFileCallback_bc1997bc(int handle, char* data, long long length) {
	return uLFileSystemReadFromFileCallbackBC1997BC(handle, data, length);
}

void ULLoggerLogMessageCallback_454e682a(ULLogLevel log_level, ULString message) {
	uLLoggerLogMessageCallback454E682A(log_level, message);
}

void ULGPUDriverBeginSynchronizeCallback_650938c() {
	uLGPUDriverBeginSynchronizeCallback650938C();
}

void ULGPUDriverEndSynchronizeCallback_f6baad4d() {
	uLGPUDriverEndSynchronizeCallbackF6BAAD4D();
}

unsigned int ULGPUDriverNextTextureIdCallback_7de045b4() {
	return uLGPUDriverNextTextureIdCallback7DE045B4();
}

void ULGPUDriverCreateTextureCallback_a32244d8(unsigned int texture_id, ULBitmap bitmap) {
	uLGPUDriverCreateTextureCallbackA32244D8(texture_id, bitmap);
}

void ULGPUDriverUpdateTextureCallback_3d7a526(unsigned int texture_id, ULBitmap bitmap) {
	uLGPUDriverUpdateTextureCallback3D7A526(texture_id, bitmap);
}

void ULGPUDriverDestroyTextureCallback_a8eea310(unsigned int texture_id) {
	uLGPUDriverDestroyTextureCallbackA8EEA310(texture_id);
}

unsigned int ULGPUDriverNextRenderBufferIdCallback_bfeb3fb8() {
	return uLGPUDriverNextRenderBufferIdCallbackBFEB3FB8();
}

void ULGPUDriverCreateRenderBufferCallback_68ee5367(unsigned int render_buffer_id, ULRenderBuffer buffer) {
	uLGPUDriverCreateRenderBufferCallback68EE5367(render_buffer_id, buffer);
}

void ULGPUDriverDestroyRenderBufferCallback_81623f13(unsigned int render_buffer_id) {
	uLGPUDriverDestroyRenderBufferCallback81623F13(render_buffer_id);
}

unsigned int ULGPUDriverNextGeometryIdCallback_5f2a8fea() {
	return uLGPUDriverNextGeometryIdCallback5F2A8FEA();
}

void ULGPUDriverCreateGeometryCallback_5957236d(unsigned int geometry_id, ULVertexBuffer vertices, ULIndexBuffer indices) {
	uLGPUDriverCreateGeometryCallback5957236D(geometry_id, vertices, indices);
}

void ULGPUDriverUpdateGeometryCallback_3f20997(unsigned int geometry_id, ULVertexBuffer vertices, ULIndexBuffer indices) {
	uLGPUDriverUpdateGeometryCallback3F20997(geometry_id, vertices, indices);
}

void ULGPUDriverDestroyGeometryCallback_cce3a508(unsigned int geometry_id) {
	uLGPUDriverDestroyGeometryCallbackCCE3A508(geometry_id);
}

void ULGPUDriverUpdateCommandListCallback_d3815a9e(ULCommandList list) {
	uLGPUDriverUpdateCommandListCallbackD3815A9E(list);
}

void ULClipboardClearCallback_eda3036a() {
	uLClipboardClearCallbackEDA3036A();
}

void ULClipboardReadPlainTextCallback_fedfb2b6(ULString result) {
	uLClipboardReadPlainTextCallbackFEDFB2B6(result);
}

void ULClipboardWritePlainTextCallback_6e8e0ca4(ULString text) {
	uLClipboardWritePlainTextCallback6E8E0CA4(text);
}

void JSTypedArrayBytesDeallocator_68d51f83(void* bytes, void* deallocatorContext) {
	jSTypedArrayBytesDeallocator68D51F83(bytes, deallocatorContext);
}

void JSObjectInitializeCallback_5793b16(JSContextRef ctx, JSObjectRef object) {
	jSObjectInitializeCallback5793B16(ctx, object);
}

void JSObjectInitializeCallbackEx_3f9a093b(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object) {
	jSObjectInitializeCallbackEx3F9A093B(ctx, jsClass, object);
}

void JSObjectFinalizeCallback_93da0aea(JSObjectRef object) {
	jSObjectFinalizeCallback93DA0AEA(object);
}

void JSObjectFinalizeCallbackEx_d64d3113(JSClassRef jsClass, JSObjectRef object) {
	jSObjectFinalizeCallbackExD64D3113(jsClass, object);
}

_Bool JSObjectHasPropertyCallback_340bfa95(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName) {
	return jSObjectHasPropertyCallback340BFA95(ctx, object, propertyName);
}

_Bool JSObjectHasPropertyCallbackEx_c35701e7(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object, JSStringRef propertyName) {
	return jSObjectHasPropertyCallbackExC35701E7(ctx, jsClass, object, propertyName);
}

JSValueRef JSObjectGetPropertyCallback_5caec716(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName, JSValueRef* exception) {
	return jSObjectGetPropertyCallback5CAEC716(ctx, object, propertyName, exception);
}

JSValueRef JSObjectGetPropertyCallbackEx_8b91eedb(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object, JSStringRef propertyName, JSValueRef* exception) {
	return jSObjectGetPropertyCallbackEx8B91EEDB(ctx, jsClass, object, propertyName, exception);
}

_Bool JSObjectSetPropertyCallback_a684f1fe(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName, JSValueRef value, JSValueRef* exception) {
	return jSObjectSetPropertyCallbackA684F1FE(ctx, object, propertyName, value, exception);
}

_Bool JSObjectSetPropertyCallbackEx_d28cf88c(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object, JSStringRef propertyName, JSValueRef value, JSValueRef* exception) {
	return jSObjectSetPropertyCallbackExD28CF88C(ctx, jsClass, object, propertyName, value, exception);
}

_Bool JSObjectDeletePropertyCallback_b0108ebe(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName, JSValueRef* exception) {
	return jSObjectDeletePropertyCallbackB0108EBE(ctx, object, propertyName, exception);
}

_Bool JSObjectDeletePropertyCallbackEx_e24fcdb0(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object, JSStringRef propertyName, JSValueRef* exception) {
	return jSObjectDeletePropertyCallbackExE24FCDB0(ctx, jsClass, object, propertyName, exception);
}

void JSObjectGetPropertyNamesCallback_e77d2329(JSContextRef ctx, JSObjectRef object, JSPropertyNameAccumulatorRef propertyNames) {
	jSObjectGetPropertyNamesCallbackE77D2329(ctx, object, propertyNames);
}

void JSObjectGetPropertyNamesCallbackEx_74285955(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object, JSPropertyNameAccumulatorRef propertyNames) {
	jSObjectGetPropertyNamesCallbackEx74285955(ctx, jsClass, object, propertyNames);
}

JSValueRef JSObjectCallAsFunctionCallback_89f9469b(JSContextRef ctx, JSObjectRef function, JSObjectRef thisObject, unsigned long int argumentCount, JSValueRef* arguments, JSValueRef* exception) {
	return jSObjectCallAsFunctionCallback89F9469B(ctx, function, thisObject, argumentCount, arguments, exception);
}

JSValueRef JSObjectCallAsFunctionCallbackEx_9f036e3c(JSContextRef ctx, JSClassRef jsClass, JSStringRef className, JSObjectRef function, JSObjectRef thisObject, unsigned long int argumentCount, JSValueRef* arguments, JSValueRef* exception) {
	return jSObjectCallAsFunctionCallbackEx9F036E3C(ctx, jsClass, className, function, thisObject, argumentCount, arguments, exception);
}

JSObjectRef JSObjectCallAsConstructorCallback_45f4b71f(JSContextRef ctx, JSObjectRef constructor, unsigned long int argumentCount, JSValueRef* arguments, JSValueRef* exception) {
	return jSObjectCallAsConstructorCallback45F4B71F(ctx, constructor, argumentCount, arguments, exception);
}

JSObjectRef JSObjectCallAsConstructorCallbackEx_a563df4(JSContextRef ctx, JSClassRef jsClass, JSObjectRef constructor, unsigned long int argumentCount, JSValueRef* arguments, JSValueRef* exception) {
	return jSObjectCallAsConstructorCallbackExA563DF4(ctx, jsClass, constructor, argumentCount, arguments, exception);
}

_Bool JSObjectHasInstanceCallback_aa527d2e(JSContextRef ctx, JSObjectRef constructor, JSValueRef possibleInstance, JSValueRef* exception) {
	return jSObjectHasInstanceCallbackAA527D2E(ctx, constructor, possibleInstance, exception);
}

_Bool JSObjectHasInstanceCallbackEx_b7bafe4e(JSContextRef ctx, JSClassRef jsClass, JSObjectRef constructor, JSValueRef possibleInstance, JSValueRef* exception) {
	return jSObjectHasInstanceCallbackExB7BAFE4E(ctx, jsClass, constructor, possibleInstance, exception);
}

JSValueRef JSObjectConvertToTypeCallback_d379d61c(JSContextRef ctx, JSObjectRef object, JSType _type, JSValueRef* exception) {
	return jSObjectConvertToTypeCallbackD379D61C(ctx, object, _type, exception);
}

JSValueRef JSObjectConvertToTypeCallbackEx_1bcea974(JSContextRef ctx, JSClassRef jsClass, JSObjectRef object, JSType _type, JSValueRef* exception) {
	return jSObjectConvertToTypeCallbackEx1BCEA974(ctx, jsClass, object, _type, exception);
}

