// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 07 Oct 2019 13:59:36 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "AppCore/CAPI.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// ULUpdateCallback_7e1c6355 is a proxy for callback ULUpdateCallback.
void ULUpdateCallback_7e1c6355(void* user_data);

// ULCloseCallback_195b2f9 is a proxy for callback ULCloseCallback.
void ULCloseCallback_195b2f9(void* user_data);

// ULResizeCallback_6e7309d9 is a proxy for callback ULResizeCallback.
void ULResizeCallback_6e7309d9(void* user_data, unsigned int width, unsigned int height);

// ULChangeTitleCallback_bd58034c is a proxy for callback ULChangeTitleCallback.
void ULChangeTitleCallback_bd58034c(void* user_data, ULView caller, ULString title);

// ULChangeURLCallback_4ec32b80 is a proxy for callback ULChangeURLCallback.
void ULChangeURLCallback_4ec32b80(void* user_data, ULView caller, ULString url);

// ULChangeTooltipCallback_12ca407 is a proxy for callback ULChangeTooltipCallback.
void ULChangeTooltipCallback_12ca407(void* user_data, ULView caller, ULString tooltip);

// ULChangeCursorCallback_1a7011df is a proxy for callback ULChangeCursorCallback.
void ULChangeCursorCallback_1a7011df(void* user_data, ULView caller, ULCursor cursor);

// ULAddConsoleMessageCallback_44b8dd01 is a proxy for callback ULAddConsoleMessageCallback.
void ULAddConsoleMessageCallback_44b8dd01(void* user_data, ULView caller, ULMessageSource source, ULMessageLevel level, ULString message, unsigned int line_number, unsigned int column_number, ULString source_id);

// ULBeginLoadingCallback_70d8c0ad is a proxy for callback ULBeginLoadingCallback.
void ULBeginLoadingCallback_70d8c0ad(void* user_data, ULView caller);

// ULFinishLoadingCallback_1ed4ecae is a proxy for callback ULFinishLoadingCallback.
void ULFinishLoadingCallback_1ed4ecae(void* user_data, ULView caller);

// ULUpdateHistoryCallback_6e105364 is a proxy for callback ULUpdateHistoryCallback.
void ULUpdateHistoryCallback_6e105364(void* user_data, ULView caller);

// ULDOMReadyCallback_6432c207 is a proxy for callback ULDOMReadyCallback.
void ULDOMReadyCallback_6432c207(void* user_data, ULView caller);

// JSTypedArrayBytesDeallocator_68d51f83 is a proxy for callback JSTypedArrayBytesDeallocator.
void JSTypedArrayBytesDeallocator_68d51f83(void* bytes, void* deallocatorContext);

// JSObjectInitializeCallback_5793b16 is a proxy for callback JSObjectInitializeCallback.
void JSObjectInitializeCallback_5793b16(JSContextRef ctx, JSObjectRef object);

// JSObjectFinalizeCallback_93da0aea is a proxy for callback JSObjectFinalizeCallback.
void JSObjectFinalizeCallback_93da0aea(JSObjectRef object);

// JSObjectHasPropertyCallback_340bfa95 is a proxy for callback JSObjectHasPropertyCallback.
_Bool JSObjectHasPropertyCallback_340bfa95(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName);

// JSObjectGetPropertyCallback_5caec716 is a proxy for callback JSObjectGetPropertyCallback.
JSValueRef JSObjectGetPropertyCallback_5caec716(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName, JSValueRef* exception);

// JSObjectSetPropertyCallback_a684f1fe is a proxy for callback JSObjectSetPropertyCallback.
_Bool JSObjectSetPropertyCallback_a684f1fe(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName, JSValueRef value, JSValueRef* exception);

// JSObjectDeletePropertyCallback_b0108ebe is a proxy for callback JSObjectDeletePropertyCallback.
_Bool JSObjectDeletePropertyCallback_b0108ebe(JSContextRef ctx, JSObjectRef object, JSStringRef propertyName, JSValueRef* exception);

// JSObjectGetPropertyNamesCallback_e77d2329 is a proxy for callback JSObjectGetPropertyNamesCallback.
void JSObjectGetPropertyNamesCallback_e77d2329(JSContextRef ctx, JSObjectRef object, JSPropertyNameAccumulatorRef propertyNames);

// JSObjectCallAsFunctionCallback_89f9469b is a proxy for callback JSObjectCallAsFunctionCallback.
JSValueRef JSObjectCallAsFunctionCallback_89f9469b(JSContextRef ctx, JSObjectRef function, JSObjectRef thisObject, unsigned long int argumentCount, JSValueRef* arguments, JSValueRef* exception);

// JSObjectCallAsConstructorCallback_45f4b71f is a proxy for callback JSObjectCallAsConstructorCallback.
JSObjectRef JSObjectCallAsConstructorCallback_45f4b71f(JSContextRef ctx, JSObjectRef constructor, unsigned long int argumentCount, JSValueRef* arguments, JSValueRef* exception);

// JSObjectHasInstanceCallback_aa527d2e is a proxy for callback JSObjectHasInstanceCallback.
_Bool JSObjectHasInstanceCallback_aa527d2e(JSContextRef ctx, JSObjectRef constructor, JSValueRef possibleInstance, JSValueRef* exception);

// JSObjectConvertToTypeCallback_d379d61c is a proxy for callback JSObjectConvertToTypeCallback.
JSValueRef JSObjectConvertToTypeCallback_d379d61c(JSContextRef ctx, JSObjectRef object, JSType _type, JSValueRef* exception);

