// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 26 Sep 2019 10:38:04 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Ultralight bindings for golang
*/
package ultralight
