// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 02 Oct 2022 19:40:55 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Ultralight bindings for golang
*/
package ultralight
