// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 02 Oct 2022 19:40:55 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package ultralight

/*
#cgo CFLAGS: -I../include
#cgo LDFLAGS: -Wl,--allow-multiple-definition -L${SRCDIR}/libs/linux/x64 -Wl,-rpath,/home/co/code/Muon/ultralight/libs/linux/x64 -lUltralightCore -lAppCore -lUltralight -lWebCore
#include "AppCore/CAPI.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// ULSettings as declared in AppCore/CAPI.h:33
type ULSettings C.ULSettings

// ULApp as declared in AppCore/CAPI.h:34
type ULApp C.ULApp

// ULWindow as declared in AppCore/CAPI.h:35
type ULWindow C.ULWindow

// ULMonitor as declared in AppCore/CAPI.h:36
type ULMonitor C.ULMonitor

// ULOverlay as declared in AppCore/CAPI.h:37
type ULOverlay C.ULOverlay

// ULUpdateCallback type as declared in AppCore/CAPI.h:148
type ULUpdateCallback func(userData unsafe.Pointer)

// ULCloseCallback type as declared in AppCore/CAPI.h:225
type ULCloseCallback func(userData unsafe.Pointer)

// ULResizeCallback type as declared in AppCore/CAPI.h:235
type ULResizeCallback func(userData unsafe.Pointer, width uint32, height uint32)

// ULChar16 type as declared in Ultralight/CAPI.h:43
type ULChar16 uint16

// ULConfig as declared in Ultralight/CAPI.h:50
type ULConfig C.ULConfig

// ULRenderer as declared in Ultralight/CAPI.h:51
type ULRenderer C.ULRenderer

// ULSession as declared in Ultralight/CAPI.h:52
type ULSession C.ULSession

// ULView as declared in Ultralight/CAPI.h:53
type ULView C.ULView

// ULBitmap as declared in Ultralight/CAPI.h:54
type ULBitmap C.ULBitmap

// ULString as declared in Ultralight/CAPI.h:55
type ULString C.ULString

// ULBuffer as declared in Ultralight/CAPI.h:56
type ULBuffer C.ULBuffer

// ULKeyEvent as declared in Ultralight/CAPI.h:57
type ULKeyEvent C.ULKeyEvent

// ULMouseEvent as declared in Ultralight/CAPI.h:58
type ULMouseEvent C.ULMouseEvent

// ULScrollEvent as declared in Ultralight/CAPI.h:59
type ULScrollEvent C.ULScrollEvent

// ULSurface as declared in Ultralight/CAPI.h:60
type ULSurface C.ULSurface

// ULBitmapSurface as declared in Ultralight/CAPI.h:61
type ULBitmapSurface C.ULBitmapSurface

// ULRect as declared in Ultralight/CAPI.h:232
type ULRect struct {
	Left           float32
	Top            float32
	Right          float32
	Bottom         float32
	ref4622ce0c    *C.ULRect
	allocs4622ce0c interface{}
}

// ULIntRect as declared in Ultralight/CAPI.h:239
type ULIntRect struct {
	Left           int32
	Top            int32
	Right          int32
	Bottom         int32
	ref79619c19    *C.ULIntRect
	allocs79619c19 interface{}
}

// ULRenderTarget as declared in Ultralight/CAPI.h:251
type ULRenderTarget struct {
	IsEmpty        bool
	Width          uint32
	Height         uint32
	TextureId      uint32
	TextureWidth   uint32
	TextureHeight  uint32
	TextureFormat  ULBitmapFormat
	UvCoords       ULRect
	RenderBufferId uint32
	ref79bb0a51    *C.ULRenderTarget
	allocs79bb0a51 interface{}
}

// ULChangeTitleCallback type as declared in Ultralight/CAPI.h:757
type ULChangeTitleCallback func(userData unsafe.Pointer, caller ULView, title ULString)

// ULChangeURLCallback type as declared in Ultralight/CAPI.h:767
type ULChangeURLCallback func(userData unsafe.Pointer, caller ULView, url ULString)

// ULChangeTooltipCallback type as declared in Ultralight/CAPI.h:777
type ULChangeTooltipCallback func(userData unsafe.Pointer, caller ULView, tooltip ULString)

// ULChangeCursorCallback type as declared in Ultralight/CAPI.h:787
type ULChangeCursorCallback func(userData unsafe.Pointer, caller ULView, cursor ULCursor)

// ULAddConsoleMessageCallback type as declared in Ultralight/CAPI.h:797
type ULAddConsoleMessageCallback func(userData unsafe.Pointer, caller ULView, source ULMessageSource, level ULMessageLevel, message ULString, lineNumber uint32, columnNumber uint32, sourceId ULString)

// ULCreateChildViewCallback type as declared in Ultralight/CAPI.h:812
type ULCreateChildViewCallback func(userData unsafe.Pointer, caller ULView, openerUrl ULString, targetUrl ULString, isPopup bool, popupRect ULIntRect) ULView

// ULBeginLoadingCallback type as declared in Ultralight/CAPI.h:833
type ULBeginLoadingCallback func(userData unsafe.Pointer, caller ULView, frameId uint64, isMainFrame bool, url ULString)

// ULFinishLoadingCallback type as declared in Ultralight/CAPI.h:844
type ULFinishLoadingCallback func(userData unsafe.Pointer, caller ULView, frameId uint64, isMainFrame bool, url ULString)

// ULFailLoadingCallback type as declared in Ultralight/CAPI.h:855
type ULFailLoadingCallback func(userData unsafe.Pointer, caller ULView, frameId uint64, isMainFrame bool, url ULString, description ULString, errorDomain ULString, errorCode int32)

// ULWindowObjectReadyCallback type as declared in Ultralight/CAPI.h:867
type ULWindowObjectReadyCallback func(userData unsafe.Pointer, caller ULView, frameId uint64, isMainFrame bool, url ULString)

// ULDOMReadyCallback type as declared in Ultralight/CAPI.h:889
type ULDOMReadyCallback func(userData unsafe.Pointer, caller ULView, frameId uint64, isMainFrame bool, url ULString)

// ULUpdateHistoryCallback type as declared in Ultralight/CAPI.h:904
type ULUpdateHistoryCallback func(userData unsafe.Pointer, caller ULView)

// ULSurfaceDefinitionCreateCallback type as declared in Ultralight/CAPI.h:1311
type ULSurfaceDefinitionCreateCallback func(width uint32, height uint32) unsafe.Pointer

// ULSurfaceDefinitionDestroyCallback type as declared in Ultralight/CAPI.h:1320
type ULSurfaceDefinitionDestroyCallback func(userData unsafe.Pointer)

// ULSurfaceDefinitionGetWidthCallback type as declared in Ultralight/CAPI.h:1328
type ULSurfaceDefinitionGetWidthCallback func(userData unsafe.Pointer) uint32

// ULSurfaceDefinitionGetHeightCallback type as declared in Ultralight/CAPI.h:1336
type ULSurfaceDefinitionGetHeightCallback func(userData unsafe.Pointer) uint32

// ULSurfaceDefinitionGetRowBytesCallback type as declared in Ultralight/CAPI.h:1346
type ULSurfaceDefinitionGetRowBytesCallback func(userData unsafe.Pointer) uint32

// ULSurfaceDefinitionGetSizeCallback type as declared in Ultralight/CAPI.h:1354
type ULSurfaceDefinitionGetSizeCallback func(userData unsafe.Pointer) uint32

// ULSurfaceDefinitionLockPixelsCallback type as declared in Ultralight/CAPI.h:1362
type ULSurfaceDefinitionLockPixelsCallback func(userData unsafe.Pointer) unsafe.Pointer

// ULSurfaceDefinitionUnlockPixelsCallback type as declared in Ultralight/CAPI.h:1372
type ULSurfaceDefinitionUnlockPixelsCallback func(userData unsafe.Pointer)

// ULSurfaceDefinitionResizeCallback type as declared in Ultralight/CAPI.h:1383
type ULSurfaceDefinitionResizeCallback func(userData unsafe.Pointer, width uint32, height uint32)

// ULSurfaceDefinition as declared in Ultralight/CAPI.h:1395
type ULSurfaceDefinition struct {
	Create         ULSurfaceDefinitionCreateCallback
	Destroy        ULSurfaceDefinitionDestroyCallback
	GetWidth       ULSurfaceDefinitionGetWidthCallback
	GetHeight      ULSurfaceDefinitionGetHeightCallback
	GetRowBytes    ULSurfaceDefinitionGetRowBytesCallback
	GetSize        ULSurfaceDefinitionGetSizeCallback
	LockPixels     ULSurfaceDefinitionLockPixelsCallback
	UnlockPixels   ULSurfaceDefinitionUnlockPixelsCallback
	Resize         ULSurfaceDefinitionResizeCallback
	ref13063f1a    *C.ULSurfaceDefinition
	allocs13063f1a interface{}
}

// ULFileHandle type as declared in Ultralight/CAPI.h:1407
type ULFileHandle int32

// ULFileSystemFileExistsCallback type as declared in Ultralight/CAPI.h:1420
type ULFileSystemFileExistsCallback func(path ULString) bool

// ULFileSystemGetFileSizeCallback type as declared in Ultralight/CAPI.h:1427
type ULFileSystemGetFileSizeCallback func(handle ULFileHandle, result []int64) bool

// ULFileSystemGetFileMimeTypeCallback type as declared in Ultralight/CAPI.h:1434
type ULFileSystemGetFileMimeTypeCallback func(path ULString, result ULString) bool

// ULFileSystemOpenFileCallback type as declared in Ultralight/CAPI.h:1444
type ULFileSystemOpenFileCallback func(path ULString, openForWriting bool) ULFileHandle

// ULFileSystemCloseFileCallback type as declared in Ultralight/CAPI.h:1451
type ULFileSystemCloseFileCallback func(handle ULFileHandle)

// ULFileSystemReadFromFileCallback type as declared in Ultralight/CAPI.h:1458
type ULFileSystemReadFromFileCallback func(handle ULFileHandle, data []byte, length int64) int64

// ULFileSystem as declared in Ultralight/CAPI.h:1467
type ULFileSystem struct {
	FileExists      ULFileSystemFileExistsCallback
	GetFileSize     ULFileSystemGetFileSizeCallback
	GetFileMimeType ULFileSystemGetFileMimeTypeCallback
	OpenFile        ULFileSystemOpenFileCallback
	CloseFile       ULFileSystemCloseFileCallback
	ReadFromFile    ULFileSystemReadFromFileCallback
	ref41d243eb     *C.ULFileSystem
	allocs41d243eb  interface{}
}

// ULLoggerLogMessageCallback type as declared in Ultralight/CAPI.h:1483
type ULLoggerLogMessageCallback func(logLevel ULLogLevel, message ULString)

// ULLogger as declared in Ultralight/CAPI.h:1487
type ULLogger struct {
	LogMessage     ULLoggerLogMessageCallback
	refd55f8aa0    *C.ULLogger
	allocsd55f8aa0 interface{}
}

// ULRenderBuffer as declared in Ultralight/CAPI.h:1503
type ULRenderBuffer struct {
	TextureId        uint32
	Width            uint32
	Height           uint32
	HasStencilBuffer bool
	HasDepthBuffer   bool
	refe8ed55f       *C.ULRenderBuffer
	allocse8ed55f    interface{}
}

// ULVertex2f4ub2f as declared in Ultralight/CAPI.h:1520
type ULVertex2f4ub2f struct {
	Pos            [2]float32
	Color          [4]byte
	Obj            [2]float32
	ref2acaf525    *C.ULVertex_2f_4ub_2f
	allocs2acaf525 interface{}
}

// ULVertex2f4ub2f2f28f as declared in Ultralight/CAPI.h:1539
type ULVertex2f4ub2f2f28f struct {
	Pos            [2]float32
	Color          [4]byte
	Tex            [2]float32
	Obj            [2]float32
	Data0          [4]float32
	Data1          [4]float32
	Data2          [4]float32
	Data3          [4]float32
	Data4          [4]float32
	Data5          [4]float32
	Data6          [4]float32
	refa40e1546    *C.ULVertex_2f_4ub_2f_2f_28f
	allocsa40e1546 interface{}
}

// ULVertexBuffer as declared in Ultralight/CAPI.h:1561
type ULVertexBuffer struct {
	Format         ULVertexBufferFormat
	Size           uint32
	Data           []byte
	ref38aa9279    *C.ULVertexBuffer
	allocs38aa9279 interface{}
}

// ULIndexType type as declared in Ultralight/CAPI.h:1566
type ULIndexType uint32

// ULIndexBuffer as declared in Ultralight/CAPI.h:1574
type ULIndexBuffer struct {
	Size           uint32
	Data           []byte
	ref8da49f64    *C.ULIndexBuffer
	allocs8da49f64 interface{}
}

// ULMatrix4x4 as declared in Ultralight/CAPI.h:1592
type ULMatrix4x4 struct {
	Data           [16]float32
	ref5420ec6b    *C.ULMatrix4x4
	allocs5420ec6b interface{}
}

// ULvec4 as declared in Ultralight/CAPI.h:1599
type ULvec4 struct {
	Value          [4]float32
	ref1faeb7f5    *C.ULvec4
	allocs1faeb7f5 interface{}
}

// ULGPUState as declared in Ultralight/CAPI.h:1652
type ULGPUState struct {
	ViewportWidth   uint32
	ViewportHeight  uint32
	Transform       ULMatrix4x4
	EnableTexturing bool
	EnableBlend     bool
	ShaderType      byte
	RenderBufferId  uint32
	Texture1Id      uint32
	Texture2Id      uint32
	Texture3Id      uint32
	UniformScalar   [8]float32
	UniformVector   [8]ULvec4
	ClipSize        byte
	Clip            [8]ULMatrix4x4
	EnableScissor   bool
	ScissorRect     ULIntRect
	ref7caf648c     *C.ULGPUState
	allocs7caf648c  interface{}
}

// ULCommand as declared in Ultralight/CAPI.h:1673
type ULCommand struct {
	CommandType    byte
	GpuState       ULGPUState
	GeometryId     uint32
	IndicesCount   uint32
	IndicesOffset  uint32
	ref7ce5cb03    *C.ULCommand
	allocs7ce5cb03 interface{}
}

// ULCommandList as declared in Ultralight/CAPI.h:1680
type ULCommandList struct {
	Size           uint32
	Commands       []ULCommand
	ref110fbbd7    *C.ULCommandList
	allocs110fbbd7 interface{}
}

// ULGPUDriverBeginSynchronizeCallback type as declared in Ultralight/CAPI.h:1688
type ULGPUDriverBeginSynchronizeCallback func()

// ULGPUDriverEndSynchronizeCallback type as declared in Ultralight/CAPI.h:1695
type ULGPUDriverEndSynchronizeCallback func()

// ULGPUDriverNextTextureIdCallback type as declared in Ultralight/CAPI.h:1702
type ULGPUDriverNextTextureIdCallback func() uint32

// ULGPUDriverCreateTextureCallback type as declared in Ultralight/CAPI.h:1713
type ULGPUDriverCreateTextureCallback func(textureId uint32, bitmap ULBitmap)

// ULGPUDriverUpdateTextureCallback type as declared in Ultralight/CAPI.h:1721
type ULGPUDriverUpdateTextureCallback func(textureId uint32, bitmap ULBitmap)

// ULGPUDriverDestroyTextureCallback type as declared in Ultralight/CAPI.h:1728
type ULGPUDriverDestroyTextureCallback func(textureId uint32)

// ULGPUDriverNextRenderBufferIdCallback type as declared in Ultralight/CAPI.h:1735
type ULGPUDriverNextRenderBufferIdCallback func() uint32

// ULGPUDriverCreateRenderBufferCallback type as declared in Ultralight/CAPI.h:1742
type ULGPUDriverCreateRenderBufferCallback func(renderBufferId uint32, buffer ULRenderBuffer)

// ULGPUDriverDestroyRenderBufferCallback type as declared in Ultralight/CAPI.h:1749
type ULGPUDriverDestroyRenderBufferCallback func(renderBufferId uint32)

// ULGPUDriverNextGeometryIdCallback type as declared in Ultralight/CAPI.h:1756
type ULGPUDriverNextGeometryIdCallback func() uint32

// ULGPUDriverCreateGeometryCallback type as declared in Ultralight/CAPI.h:1763
type ULGPUDriverCreateGeometryCallback func(geometryId uint32, vertices ULVertexBuffer, indices ULIndexBuffer)

// ULGPUDriverUpdateGeometryCallback type as declared in Ultralight/CAPI.h:1772
type ULGPUDriverUpdateGeometryCallback func(geometryId uint32, vertices ULVertexBuffer, indices ULIndexBuffer)

// ULGPUDriverDestroyGeometryCallback type as declared in Ultralight/CAPI.h:1780
type ULGPUDriverDestroyGeometryCallback func(geometryId uint32)

// ULGPUDriverUpdateCommandListCallback type as declared in Ultralight/CAPI.h:1787
type ULGPUDriverUpdateCommandListCallback func(list ULCommandList)

// ULGPUDriver as declared in Ultralight/CAPI.h:1804
type ULGPUDriver struct {
	BeginSynchronize    ULGPUDriverBeginSynchronizeCallback
	EndSynchronize      ULGPUDriverEndSynchronizeCallback
	NextTextureId       ULGPUDriverNextTextureIdCallback
	CreateTexture       ULGPUDriverCreateTextureCallback
	UpdateTexture       ULGPUDriverUpdateTextureCallback
	DestroyTexture      ULGPUDriverDestroyTextureCallback
	NextRenderBufferId  ULGPUDriverNextRenderBufferIdCallback
	CreateRenderBuffer  ULGPUDriverCreateRenderBufferCallback
	DestroyRenderBuffer ULGPUDriverDestroyRenderBufferCallback
	NextGeometryId      ULGPUDriverNextGeometryIdCallback
	CreateGeometry      ULGPUDriverCreateGeometryCallback
	UpdateGeometry      ULGPUDriverUpdateGeometryCallback
	DestroyGeometry     ULGPUDriverDestroyGeometryCallback
	UpdateCommandList   ULGPUDriverUpdateCommandListCallback
	refdfd8a4f0         *C.ULGPUDriver
	allocsdfd8a4f0      interface{}
}

// ULClipboardClearCallback type as declared in Ultralight/CAPI.h:1830
type ULClipboardClearCallback func()

// ULClipboardReadPlainTextCallback type as declared in Ultralight/CAPI.h:1839
type ULClipboardReadPlainTextCallback func(result ULString)

// ULClipboardWritePlainTextCallback type as declared in Ultralight/CAPI.h:1846
type ULClipboardWritePlainTextCallback func(text ULString)

// ULClipboard as declared in Ultralight/CAPI.h:1852
type ULClipboard struct {
	Clear          ULClipboardClearCallback
	ReadPlainText  ULClipboardReadPlainTextCallback
	WritePlainText ULClipboardWritePlainTextCallback
	refdcb753f     *C.ULClipboard
	allocsdcb753f  interface{}
}

// JSContextGroupRef as declared in JavaScriptCore/JSBase.h:40
type JSContextGroupRef C.JSContextGroupRef

// JSContextRef as declared in JavaScriptCore/JSBase.h:43
type JSContextRef C.JSContextRef

// JSGlobalContextRef as declared in JavaScriptCore/JSBase.h:46
type JSGlobalContextRef C.JSGlobalContextRef

// JSStringRef as declared in JavaScriptCore/JSBase.h:49
type JSStringRef C.JSStringRef

// JSClassRef as declared in JavaScriptCore/JSBase.h:52
type JSClassRef C.JSClassRef

// JSPropertyNameArrayRef as declared in JavaScriptCore/JSBase.h:55
type JSPropertyNameArrayRef C.JSPropertyNameArrayRef

// JSPropertyNameAccumulatorRef as declared in JavaScriptCore/JSBase.h:58
type JSPropertyNameAccumulatorRef C.JSPropertyNameAccumulatorRef

// JSTypedArrayBytesDeallocator type as declared in JavaScriptCore/JSBase.h:61
type JSTypedArrayBytesDeallocator func(bytes unsafe.Pointer, deallocatorContext unsafe.Pointer)

// JSValueRef as declared in JavaScriptCore/JSBase.h:66
type JSValueRef C.JSValueRef

// JSObjectRef as declared in JavaScriptCore/JSBase.h:69
type JSObjectRef C.JSObjectRef

// JSPropertyAttributes type as declared in JavaScriptCore/JSObjectRef.h:61
type JSPropertyAttributes uint32

// JSClassAttributes type as declared in JavaScriptCore/JSObjectRef.h:77
type JSClassAttributes uint32

// JSObjectInitializeCallback type as declared in JavaScriptCore/JSObjectRef.h:92
type JSObjectInitializeCallback func(ctx JSContextRef, object JSObjectRef)

// JSObjectInitializeCallbackEx type as declared in JavaScriptCore/JSObjectRef.h:96
type JSObjectInitializeCallbackEx func(ctx JSContextRef, jsClass JSClassRef, object JSObjectRef)

// JSObjectFinalizeCallback type as declared in JavaScriptCore/JSObjectRef.h:114
type JSObjectFinalizeCallback func(object JSObjectRef)

// JSObjectFinalizeCallbackEx type as declared in JavaScriptCore/JSObjectRef.h:118
type JSObjectFinalizeCallbackEx func(jsClass JSClassRef, object JSObjectRef)

// JSObjectHasPropertyCallback type as declared in JavaScriptCore/JSObjectRef.h:138
type JSObjectHasPropertyCallback func(ctx JSContextRef, object JSObjectRef, propertyName JSStringRef) bool

// JSObjectHasPropertyCallbackEx type as declared in JavaScriptCore/JSObjectRef.h:142
type JSObjectHasPropertyCallbackEx func(ctx JSContextRef, jsClass JSClassRef, object JSObjectRef, propertyName JSStringRef) bool

// JSObjectGetPropertyCallback type as declared in JavaScriptCore/JSObjectRef.h:159
type JSObjectGetPropertyCallback func(ctx JSContextRef, object JSObjectRef, propertyName JSStringRef, exception []JSValueRef) JSValueRef

// JSObjectGetPropertyCallbackEx type as declared in JavaScriptCore/JSObjectRef.h:163
type JSObjectGetPropertyCallbackEx func(ctx JSContextRef, jsClass JSClassRef, object JSObjectRef, propertyName JSStringRef, exception []JSValueRef) JSValueRef

// JSObjectSetPropertyCallback type as declared in JavaScriptCore/JSObjectRef.h:181
type JSObjectSetPropertyCallback func(ctx JSContextRef, object JSObjectRef, propertyName JSStringRef, value JSValueRef, exception []JSValueRef) bool

// JSObjectSetPropertyCallbackEx type as declared in JavaScriptCore/JSObjectRef.h:185
type JSObjectSetPropertyCallbackEx func(ctx JSContextRef, jsClass JSClassRef, object JSObjectRef, propertyName JSStringRef, value JSValueRef, exception []JSValueRef) bool

// JSObjectDeletePropertyCallback type as declared in JavaScriptCore/JSObjectRef.h:202
type JSObjectDeletePropertyCallback func(ctx JSContextRef, object JSObjectRef, propertyName JSStringRef, exception []JSValueRef) bool

// JSObjectDeletePropertyCallbackEx type as declared in JavaScriptCore/JSObjectRef.h:206
type JSObjectDeletePropertyCallbackEx func(ctx JSContextRef, jsClass JSClassRef, object JSObjectRef, propertyName JSStringRef, exception []JSValueRef) bool

// JSObjectGetPropertyNamesCallback type as declared in JavaScriptCore/JSObjectRef.h:223
type JSObjectGetPropertyNamesCallback func(ctx JSContextRef, object JSObjectRef, propertyNames JSPropertyNameAccumulatorRef)

// JSObjectGetPropertyNamesCallbackEx type as declared in JavaScriptCore/JSObjectRef.h:227
type JSObjectGetPropertyNamesCallbackEx func(ctx JSContextRef, jsClass JSClassRef, object JSObjectRef, propertyNames JSPropertyNameAccumulatorRef)

// JSObjectCallAsFunctionCallback type as declared in JavaScriptCore/JSObjectRef.h:248
type JSObjectCallAsFunctionCallback func(ctx JSContextRef, function JSObjectRef, thisObject JSObjectRef, argumentCount uint32, arguments []JSValueRef, exception []JSValueRef) JSValueRef

// JSObjectCallAsFunctionCallbackEx type as declared in JavaScriptCore/JSObjectRef.h:254
type JSObjectCallAsFunctionCallbackEx func(ctx JSContextRef, jsClass JSClassRef, className JSStringRef, function JSObjectRef, thisObject JSObjectRef, argumentCount uint32, arguments []JSValueRef, exception []JSValueRef) JSValueRef

// JSObjectCallAsConstructorCallback type as declared in JavaScriptCore/JSObjectRef.h:274
type JSObjectCallAsConstructorCallback func(ctx JSContextRef, constructor JSObjectRef, argumentCount uint32, arguments []JSValueRef, exception []JSValueRef) JSObjectRef

// JSObjectCallAsConstructorCallbackEx type as declared in JavaScriptCore/JSObjectRef.h:278
type JSObjectCallAsConstructorCallbackEx func(ctx JSContextRef, jsClass JSClassRef, constructor JSObjectRef, argumentCount uint32, arguments []JSValueRef, exception []JSValueRef) JSObjectRef

// JSObjectHasInstanceCallback type as declared in JavaScriptCore/JSObjectRef.h:299
type JSObjectHasInstanceCallback func(ctx JSContextRef, constructor JSObjectRef, possibleInstance JSValueRef, exception []JSValueRef) bool

// JSObjectHasInstanceCallbackEx type as declared in JavaScriptCore/JSObjectRef.h:303
type JSObjectHasInstanceCallbackEx func(ctx JSContextRef, jsClass JSClassRef, constructor JSObjectRef, possibleInstance JSValueRef, exception []JSValueRef) bool

// JSObjectConvertToTypeCallback type as declared in JavaScriptCore/JSObjectRef.h:322
type JSObjectConvertToTypeCallback func(ctx JSContextRef, object JSObjectRef, kind JSType, exception []JSValueRef) JSValueRef

// JSObjectConvertToTypeCallbackEx type as declared in JavaScriptCore/JSObjectRef.h:326
type JSObjectConvertToTypeCallbackEx func(ctx JSContextRef, jsClass JSClassRef, object JSObjectRef, kind JSType, exception []JSValueRef) JSValueRef

// JSStaticValue as declared in JavaScriptCore/JSObjectRef.h:341
type JSStaticValue struct {
	Name           string
	GetProperty    JSObjectGetPropertyCallback
	SetProperty    JSObjectSetPropertyCallback
	Attributes     JSPropertyAttributes
	ref34655956    *C.JSStaticValue
	allocs34655956 interface{}
}

// JSStaticValueEx as declared in JavaScriptCore/JSObjectRef.h:349
type JSStaticValueEx struct {
	Name           string
	GetPropertyEx  JSObjectGetPropertyCallbackEx
	SetPropertyEx  JSObjectSetPropertyCallbackEx
	Attributes     JSPropertyAttributes
	ref6c5f7756    *C.JSStaticValueEx
	allocs6c5f7756 interface{}
}

// JSStaticFunction as declared in JavaScriptCore/JSObjectRef.h:362
type JSStaticFunction struct {
	Name           string
	CallAsFunction JSObjectCallAsFunctionCallback
	Attributes     JSPropertyAttributes
	ref6b5f4953    *C.JSStaticFunction
	allocs6b5f4953 interface{}
}

// JSStaticFunctionEx as declared in JavaScriptCore/JSObjectRef.h:369
type JSStaticFunctionEx struct {
	Name             string
	CallAsFunctionEx JSObjectCallAsFunctionCallbackEx
	Attributes       JSPropertyAttributes
	refc9fcc4d       *C.JSStaticFunctionEx
	allocsc9fcc4d    interface{}
}

// JSClassDefinition as declared in JavaScriptCore/JSObjectRef.h:448
type JSClassDefinition struct {
	Version        int32
	Attributes     JSClassAttributes
	ClassName      string
	ParentClass    JSClassRef
	PrivateData    unsafe.Pointer
	ref192c18d5    *C.JSClassDefinition
	allocs192c18d5 interface{}
}

// JSChar type as declared in JavaScriptCore/JSStringRef.h:49
type JSChar uint16
